### ISSUE TITLE
When choosing teams to copy, all options should be DESELCTED by default

### ISSUE THREAD

**Issue by wifelette** [ember-learn/gh-team-copy#4]
Right now they're all selected, leading to confusion since the prompt tells you to select what you want. Also, it's more likely you're only adding one or two teams, not all, so that's a quicker way anyway.

**Comment by acorncom** [comment]
For context, the Ember org has 100 teams, so having to deselect all teams is a nuisance

**Comment by sivakumar-kailasam** [comment]
Inquirer seems to be having the "select/deselect all" feature in the works, SBoudrias/Inquirer.js#347. Once that lands there, we can probably add those two options and deselect all by default.

**Comment by sivakumar-kailasam** [comment]
Inquirer now supports 'deselect all' which I've upgraded to in a patch release. So by default we still select all teams but users can now press i and proceed to select ones they're interested in.

<img width="704" alt="screenshot 2016-10-09 22 51 48" src="https://cloud.githubusercontent.com/assets/604117/19222313/01964a8e-8e73-11e6-999d-6e0ff9437c43.png">

If we need to leave all unselected by default, do reopen this issue and I'll make it the default behavior.

**Comment by acorncom** [comment]
@sivakumar-kailasam leaving all unselected by default sounded like the ideal use case, let's shift to doing things that way ...

**Comment by sivakumar-kailasam** [comment]
Fixed in v6.0.3.
