### ISSUE TITLE
After you sync a team, confirmation message should remind that the people added still need to *accept* the invites

### ISSUE THREAD

**Issue by wifelette** [ember-learn/gh-team-copy#5]
...lest it appear broken when you go the website to check if all those people were in fact added :)

**Comment by sivakumar-kailasam** [comment]
Added a [message](https://github.com/ember-learn/gh-team-copy/blob/c61278c5aa403e3113fdd71534f22af74adbe7da/src/summary.js#L25) for this,
`console.log(`Members who don't belong to the target team have been invited.
They should ${chalk.bold('accept')} their invites to have repo access.`);`
