### ISSUE TITLE
can this tool be re-run to "update" ?

### ISSUE THREAD

**Issue by stefanpenner** [ember-learn/gh-team-copy#6]
If so what are the semantics of collisions/removals etc?

**Comment by sivakumar-kailasam** [comment]
As of now, it will not remove members already in the team. If needed we can do a diff and ask the user to select those who need to be removed.

**Comment by stefanpenner** [comment]
So, it is safe to run multiple times, but it is a non-destructive one-way sync?

**Comment by sivakumar-kailasam** [comment]
Just did a dry run, was wrong about what I said. I'll fix this today.

**Comment by stefanpenner** [comment]
I suspect the best bet (for a first pass) is:
1. ability to do non-destructive update
2. list "destructive" operations that could not be applied manually

---

For the future, we may want to consider some sort of more power-full syncing. (but not something that blocks us from being successful today) One approach would be to have a "master" which is a single config file we commit to git (private repo maybe), and when we add users, we add it via that. then run the script which applies the sync to all the orgs.

**Comment by sivakumar-kailasam** [comment]
Non destructive updates are ensured now. Will take @acorncom's help to collect any other feedback on the tool from core and address them via #7.
